{

gROOT->ProcessLine(".x CMSStyle.C");
CMSStyle();

TFile *fNew = new TFile("NEWConstants_validationHists_global.root");
TFile *fOld = new TFile("DBConstants_validationHists_global.root");

TLegend* leg = new TLegend(0.20,0.75,0.38,0.91,"","brNDC");
leg->SetTextFont(132);
leg->SetFillColor(0);
leg->SetBorderSize(0);


TH1F * hSResidminus11_N = (TH1F*)fNew->Get("Resolution/hSResid-11");
TH1F * hSResidminus11_O = (TH1F*)fOld->Get("Resolution/hSResid-11");
std::cout<<"h->Fill(endcap[0],"<<hSResidminus11_N->GetMean()<<");"<<std::endl;
std::cout<<"h->SetBinError(0,"<<hSResidminus11_N->GetRMS()<<");"<<std::endl;
std::cout<<hSResidminus11_N->GetMean()<<std::endl;
std::cout<<hSResidminus11_N->GetRMS()<<std::endl;
hSResidminus11_N->SetLineColor(4);
hSResidminus11_N->SetMarkerColor(4);
hSResidminus11_N->SetLineWidth(2);
hSResidminus11_N->SetMarkerSize(.5);
hSResidminus11_O->SetFillColor(18);
hSResidminus11_O->GetXaxis()->SetTitle("Position (cm)");
hSResidminus11_O->Draw("");
hSResidminus11_N->Draw("epSAME");
leg->AddEntry(hSResidminus11_O,"Old Const.");
leg->AddEntry(hSResidminus11_N,"New Const.");
leg->Draw("SAME");
c1->Print("hSResidminus11.png");

TH1F * hSResidminus12_N = (TH1F*)fNew->Get("Resolution/hSResid-12");
TH1F * hSResidminus12_O = (TH1F*)fOld->Get("Resolution/hSResid-12");
std::cout<<"h->Fill(endcap[1],"<<hSResidminus12_N->GetMean()<<");"<<std::endl;
std::cout<<"h->SetBinError(1,"<<hSResidminus12_N->GetRMS()<<");"<<std::endl;
std::cout<<hSResidminus12_N->GetMean()<<std::endl;
std::cout<<hSResidminus12_N->GetRMS()<<std::endl;
hSResidminus12_N->SetLineColor(4);
hSResidminus12_N->SetMarkerColor(4);
hSResidminus12_N->SetLineWidth(2);
hSResidminus12_N->SetMarkerSize(.5);
hSResidminus12_O->SetFillColor(18);
hSResidminus12_O->GetXaxis()->SetTitle("Position (cm)");
hSResidminus12_O->Draw("");
hSResidminus12_N->Draw("epSAME");
leg->Draw("SAME");
c1->Print("hSResidminus12.png");

TH1F * hSResidminus13_N = (TH1F*)fNew->Get("Resolution/hSResid-13");
TH1F * hSResidminus13_O = (TH1F*)fOld->Get("Resolution/hSResid-13");
std::cout<<"h->Fill(endcap[2],"<<hSResidminus13_N->GetMean()<<");"<<std::endl;
std::cout<<"h->SetBinError(2,"<<hSResidminus13_N->GetRMS()<<");"<<std::endl;
std::cout<<hSResidminus13_N->GetMean()<<std::endl;
std::cout<<hSResidminus13_N->GetRMS()<<std::endl;
hSResidminus13_N->SetLineColor(4);
hSResidminus13_N->SetMarkerColor(4);
hSResidminus13_N->SetLineWidth(2);
hSResidminus13_N->SetMarkerSize(.5);
hSResidminus13_O->SetFillColor(18);
hSResidminus13_O->GetXaxis()->SetTitle("Position (cm)");
hSResidminus13_O->Draw("");
hSResidminus13_N->Draw("epSAME");
leg->Draw("SAME");
c1->Print("hSResidminus13.png");

TH1F * hSResidminus14_N = (TH1F*)fNew->Get("Resolution/hSResid-14");
TH1F * hSResidminus14_O = (TH1F*)fOld->Get("Resolution/hSResid-14");
std::cout<<"h->Fill(endcap[3],"<<hSResidminus14_N->GetMean()<<");"<<std::endl;
std::cout<<"h->SetBinError(3,"<<hSResidminus14_N->GetRMS()<<");"<<std::endl;
std::cout<<hSResidminus14_N->GetMean()<<std::endl;
std::cout<<hSResidminus14_N->GetRMS()<<std::endl;
hSResidminus14_N->SetLineColor(4);
hSResidminus14_N->SetMarkerColor(4);
hSResidminus14_N->SetLineWidth(2);
hSResidminus14_N->SetMarkerSize(.5);
hSResidminus14_O->SetFillColor(18);
hSResidminus14_O->GetXaxis()->SetTitle("Position (cm)");
hSResidminus14_O->Draw("");
hSResidminus14_N->Draw("epSAME");
leg->Draw("SAME");
c1->Print("hSResidminus14.png");

TH1F * hSResidminus21_N = (TH1F*)fNew->Get("Resolution/hSResid-21");
TH1F * hSResidminus21_O = (TH1F*)fOld->Get("Resolution/hSResid-21");
std::cout<<"h->Fill(endcap[4],"<<hSResidminus21_N->GetMean()<<");"<<std::endl;
std::cout<<"h->SetBinError(4,"<<hSResidminus21_N->GetRMS()<<");"<<std::endl;
std::cout<<hSResidminus21_N->GetMean()<<std::endl;
std::cout<<hSResidminus21_N->GetRMS()<<std::endl;
hSResidminus21_N->SetLineColor(4);
hSResidminus21_N->SetMarkerColor(4);
hSResidminus21_N->SetLineWidth(2);
hSResidminus21_N->SetMarkerSize(.5);
hSResidminus21_O->SetFillColor(18);
hSResidminus21_O->GetXaxis()->SetTitle("Position (cm)");
hSResidminus21_O->Draw("");
hSResidminus21_N->Draw("epSAME");
leg->Draw("SAME");
c1->Print("hSResidminus21.png");

TH1F * hSResidminus22_N = (TH1F*)fNew->Get("Resolution/hSResid-22");
TH1F * hSResidminus22_O = (TH1F*)fOld->Get("Resolution/hSResid-22");
std::cout<<"h->Fill(endcap[5],"<<hSResidminus22_N->GetMean()<<");"<<std::endl;
std::cout<<"h->SetBinError(5,"<<hSResidminus22_N->GetRMS()<<");"<<std::endl;
std::cout<<hSResidminus22_N->GetMean()<<std::endl;
std::cout<<hSResidminus22_N->GetRMS()<<std::endl;
hSResidminus22_N->SetLineColor(4);
hSResidminus22_N->SetMarkerColor(4);
hSResidminus22_N->SetLineWidth(2);
hSResidminus22_N->SetMarkerSize(.5);
hSResidminus22_O->SetFillColor(18);
hSResidminus22_O->GetXaxis()->SetTitle("Position (cm)");
hSResidminus22_O->Draw("");
hSResidminus22_N->Draw("epSAME");
leg->Draw("SAME");
c1->Print("hSResidminus22.png");

TH1F * hSResidminus31_N = (TH1F*)fNew->Get("Resolution/hSResid-31");
TH1F * hSResidminus31_O = (TH1F*)fOld->Get("Resolution/hSResid-31");
std::cout<<"h->Fill(endcap[6],"<<hSResidminus31_N->GetMean()<<");"<<std::endl;
std::cout<<"h->SetBinError(6,"<<hSResidminus31_N->GetRMS()<<");"<<std::endl;
std::cout<<hSResidminus31_N->GetMean()<<std::endl;
std::cout<<hSResidminus31_N->GetRMS()<<std::endl;
hSResidminus31_N->SetLineColor(4);
hSResidminus31_N->SetMarkerColor(4);
hSResidminus31_N->SetLineWidth(2);
hSResidminus31_N->SetMarkerSize(.5);
hSResidminus31_O->SetFillColor(18);
hSResidminus31_O->GetXaxis()->SetTitle("Position (cm)");
hSResidminus31_O->Draw("");
hSResidminus31_N->Draw("epSAME");
leg->Draw("SAME");
c1->Print("hSResidminus31.png");

TH1F * hSResidminus32_N = (TH1F*)fNew->Get("Resolution/hSResid-32");
TH1F * hSResidminus32_O = (TH1F*)fOld->Get("Resolution/hSResid-32");
std::cout<<"h->Fill(endcap[7],"<<hSResidminus32_N->GetMean()<<");"<<std::endl;
std::cout<<"h->SetBinError(7,"<<hSResidminus32_N->GetRMS()<<");"<<std::endl;
std::cout<<hSResidminus32_N->GetMean()<<std::endl;
std::cout<<hSResidminus32_N->GetRMS()<<std::endl;
hSResidminus32_N->SetLineColor(4);
hSResidminus32_N->SetMarkerColor(4);
hSResidminus32_N->SetLineWidth(2);
hSResidminus32_N->SetMarkerSize(.5);
hSResidminus32_O->SetFillColor(18);
hSResidminus32_O->GetXaxis()->SetTitle("Position (cm)");
hSResidminus32_O->Draw("");
hSResidminus32_N->Draw("epSAME");
leg->Draw("SAME");
c1->Print("hSResidminus32.png");

TH1F * hSResidminus41_N = (TH1F*)fNew->Get("Resolution/hSResid-41");
TH1F * hSResidminus41_O = (TH1F*)fOld->Get("Resolution/hSResid-41");
std::cout<<"h->Fill(endcap[8],"<<hSResidminus41_N->GetMean()<<");"<<std::endl;
std::cout<<"h->SetBinError(8,"<<hSResidminus41_N->GetRMS()<<");"<<std::endl;
std::cout<<hSResidminus41_N->GetMean()<<std::endl;
std::cout<<hSResidminus41_N->GetRMS()<<std::endl;
hSResidminus41_N->SetLineColor(4);
hSResidminus41_N->SetMarkerColor(4);
hSResidminus41_N->SetLineWidth(2);
hSResidminus41_N->SetMarkerSize(.5);
hSResidminus41_O->SetFillColor(18);
hSResidminus41_O->GetXaxis()->SetTitle("Position (cm)");
hSResidminus41_O->Draw("");
hSResidminus41_N->Draw("epSAME");
leg->Draw("SAME");
c1->Print("hSResidminus41.png");

TH1F * hSResidplus11_N = (TH1F*)fNew->Get("Resolution/hSResid+11");
TH1F * hSResidplus11_O = (TH1F*)fOld->Get("Resolution/hSResid+11");
std::cout<<"h->Fill(endcap[9],"<<hSResidplus11_N->GetMean()<<");"<<std::endl;
std::cout<<"h->SetBinError(9,"<<hSResidplus11_N->GetRMS()<<");"<<std::endl;
std::cout<<hSResidplus11_N->GetMean()<<std::endl;
std::cout<<hSResidplus11_N->GetRMS()<<std::endl;
hSResidplus11_N->SetLineColor(4);
hSResidplus11_N->SetMarkerColor(4);
hSResidplus11_N->SetLineWidth(2);
hSResidplus11_N->SetMarkerSize(.5);
hSResidplus11_O->SetFillColor(18);
hSResidplus11_O->GetXaxis()->SetTitle("Position (cm)");
hSResidplus11_O->Draw("");
hSResidplus11_N->Draw("epSAME");
leg->Draw("SAME");
c1->Print("hSResidplus11.png");

TH1F * hSResidplus12_N = (TH1F*)fNew->Get("Resolution/hSResid+12");
TH1F * hSResidplus12_O = (TH1F*)fOld->Get("Resolution/hSResid+12");
std::cout<<"h->Fill(endcap[10],"<<hSResidplus12_N->GetMean()<<");"<<std::endl;
std::cout<<"h->SetBinError(10,"<<hSResidplus12_N->GetRMS()<<");"<<std::endl;
std::cout<<hSResidplus12_N->GetMean()<<std::endl;
std::cout<<hSResidplus12_N->GetRMS()<<std::endl;
hSResidplus12_N->SetLineColor(4);
hSResidplus12_N->SetMarkerColor(4);
hSResidplus12_N->SetLineWidth(2);
hSResidplus12_N->SetMarkerSize(.5);
hSResidplus12_O->SetFillColor(18);
hSResidplus12_O->GetXaxis()->SetTitle("Position (cm)");
hSResidplus12_O->Draw("");
hSResidplus12_N->Draw("epSAME");
leg->Draw("SAME");
c1->Print("hSResidplus12.png");

TH1F * hSResidplus13_N = (TH1F*)fNew->Get("Resolution/hSResid+13");
TH1F * hSResidplus13_O = (TH1F*)fOld->Get("Resolution/hSResid+13");
std::cout<<"h->Fill(endcap[11],"<<hSResidplus13_N->GetMean()<<");"<<std::endl;
std::cout<<"h->SetBinError(11,"<<hSResidplus13_N->GetRMS()<<");"<<std::endl;
std::cout<<hSResidplus13_N->GetMean()<<std::endl;
std::cout<<hSResidplus13_N->GetRMS()<<std::endl;
hSResidplus13_N->SetLineColor(4);
hSResidplus13_N->SetMarkerColor(4);
hSResidplus13_N->SetLineWidth(2);
hSResidplus13_N->SetMarkerSize(.5);
hSResidplus13_O->SetFillColor(18);
hSResidplus13_O->GetXaxis()->SetTitle("Position (cm)");
hSResidplus13_O->Draw("");
hSResidplus13_N->Draw("epSAME");
leg->Draw("SAME");
c1->Print("hSResidplus13.png");

TH1F * hSResidplus14_N = (TH1F*)fNew->Get("Resolution/hSResid+14");
TH1F * hSResidplus14_O = (TH1F*)fOld->Get("Resolution/hSResid+14");
std::cout<<"h->Fill(endcap[12],"<<hSResidplus14_N->GetMean()<<");"<<std::endl;
std::cout<<"h->SetBinError(12,"<<hSResidplus14_N->GetRMS()<<");"<<std::endl;
std::cout<<hSResidplus14_N->GetMean()<<std::endl;
std::cout<<hSResidplus14_N->GetRMS()<<std::endl;
hSResidplus14_N->SetLineColor(4);
hSResidplus14_N->SetMarkerColor(4);
hSResidplus14_N->SetLineWidth(2);
hSResidplus14_N->SetMarkerSize(.5);
hSResidplus14_O->SetFillColor(18);
hSResidplus14_O->GetXaxis()->SetTitle("Position (cm)");
hSResidplus14_O->Draw("");
hSResidplus14_N->Draw("epSAME");
leg->Draw("SAME");
c1->Print("hSResidplus14.png");

TH1F * hSResidplus21_N = (TH1F*)fNew->Get("Resolution/hSResid+21");
TH1F * hSResidplus21_O = (TH1F*)fOld->Get("Resolution/hSResid+21");
std::cout<<"h->Fill(endcap[13],"<<hSResidplus21_N->GetMean()<<");"<<std::endl;
std::cout<<"h->SetBinError(13,"<<hSResidplus21_N->GetRMS()<<");"<<std::endl;
std::cout<<hSResidplus21_N->GetMean()<<std::endl;
std::cout<<hSResidplus21_N->GetRMS()<<std::endl;
hSResidplus21_N->SetLineColor(4);
hSResidplus21_N->SetMarkerColor(4);
hSResidplus21_N->SetLineWidth(2);
hSResidplus21_N->SetMarkerSize(.5);
hSResidplus21_O->SetFillColor(18);
hSResidplus21_O->GetXaxis()->SetTitle("Position (cm)");
hSResidplus21_O->Draw("");
hSResidplus21_N->Draw("epSAME");
leg->Draw("SAME");
c1->Print("hSResidplus21.png");

TH1F * hSResidplus22_N = (TH1F*)fNew->Get("Resolution/hSResid+22");
TH1F * hSResidplus22_O = (TH1F*)fOld->Get("Resolution/hSResid+22");
std::cout<<"h->Fill(endcap[14],"<<hSResidplus22_N->GetMean()<<");"<<std::endl;
std::cout<<"h->SetBinError(14,"<<hSResidplus22_N->GetRMS()<<");"<<std::endl;
std::cout<<hSResidplus22_N->GetMean()<<std::endl;
std::cout<<hSResidplus22_N->GetRMS()<<std::endl;
hSResidplus22_N->SetLineColor(4);
hSResidplus22_N->SetMarkerColor(4);
hSResidplus22_N->SetLineWidth(2);
hSResidplus22_N->SetMarkerSize(.5);
hSResidplus22_O->SetFillColor(18);
hSResidplus22_O->GetXaxis()->SetTitle("Position (cm)");
hSResidplus22_O->Draw("");
hSResidplus22_N->Draw("epSAME");
leg->Draw("SAME");
c1->Print("hSResidplus22.png");

TH1F * hSResidplus31_N = (TH1F*)fNew->Get("Resolution/hSResid+31");
TH1F * hSResidplus31_O = (TH1F*)fOld->Get("Resolution/hSResid+31");
std::cout<<"h->Fill(endcap[15],"<<hSResidplus31_N->GetMean()<<");"<<std::endl;
std::cout<<"h->SetBinError(15,"<<hSResidplus31_N->GetRMS()<<");"<<std::endl;
std::cout<<hSResidplus31_N->GetMean()<<std::endl;
std::cout<<hSResidplus31_N->GetRMS()<<std::endl;
hSResidplus31_N->SetLineColor(4);
hSResidplus31_N->SetMarkerColor(4);
hSResidplus31_N->SetLineWidth(2);
hSResidplus31_N->SetMarkerSize(.5);
hSResidplus31_O->SetFillColor(18);
hSResidplus31_O->GetXaxis()->SetTitle("Position (cm)");
hSResidplus31_O->Draw("");
hSResidplus31_N->Draw("epSAME");
leg->Draw("SAME");
c1->Print("hSResidplus31.png");

TH1F * hSResidplus32_N = (TH1F*)fNew->Get("Resolution/hSResid+32");
TH1F * hSResidplus32_O = (TH1F*)fOld->Get("Resolution/hSResid+32");
std::cout<<"h->Fill(endcap[16],"<<hSResidplus32_N->GetMean()<<");"<<std::endl;
std::cout<<"h->SetBinError(16,"<<hSResidplus32_N->GetRMS()<<");"<<std::endl;
std::cout<<hSResidplus32_N->GetMean()<<std::endl;
std::cout<<hSResidplus32_N->GetRMS()<<std::endl;
hSResidplus32_N->SetLineColor(4);
hSResidplus32_N->SetMarkerColor(4);
hSResidplus32_N->SetLineWidth(2);
hSResidplus32_N->SetMarkerSize(.5);
hSResidplus32_O->SetFillColor(18);
hSResidplus32_O->GetXaxis()->SetTitle("Position (cm)");
hSResidplus32_O->Draw("");
hSResidplus32_N->Draw("epSAME");
leg->Draw("SAME");
c1->Print("hSResidplus32.png");

TH1F * hSResidplus41_N = (TH1F*)fNew->Get("Resolution/hSResid+41");
TH1F * hSResidplus41_O = (TH1F*)fOld->Get("Resolution/hSResid+41");
std::cout<<"h->Fill(endcap[17],"<<hSResidplus41_N->GetMean()<<");"<<std::endl;
std::cout<<"h->SetBinError(17,"<<hSResidplus41_N->GetRMS()<<");"<<std::endl;
std::cout<<hSResidplus41_N->GetMean()<<std::endl;
std::cout<<hSResidplus41_N->GetRMS()<<std::endl;
hSResidplus41_N->SetLineColor(4);
hSResidplus41_N->SetMarkerColor(4);
hSResidplus41_N->SetLineWidth(2);
hSResidplus41_N->SetMarkerSize(.5);
hSResidplus41_O->SetFillColor(18);
hSResidplus41_O->GetXaxis()->SetTitle("Position (cm)");
hSResidplus41_O->Draw("");
hSResidplus41_N->Draw("epSAME");
leg->Draw("SAME");
c1->Print("hSResidplus41.png");

TH1F * hSResidplus42_N = (TH1F*)fNew->Get("Resolution/hSResid+42");
TH1F * hSResidplus42_O = (TH1F*)fOld->Get("Resolution/hSResid+42");
std::cout<<"h->Fill(endcap[18],"<<hSResidplus42_N->GetMean()<<");"<<std::endl;
std::cout<<"h->SetBinError(18,"<<hSResidplus42_N->GetRMS()<<");"<<std::endl;
std::cout<<hSResidplus42_N->GetMean()<<std::endl;
std::cout<<hSResidplus42_N->GetRMS()<<std::endl;
hSResidplus42_N->SetLineColor(4);
hSResidplus42_N->SetMarkerColor(4);
hSResidplus42_N->SetLineWidth(2);
hSResidplus42_N->SetMarkerSize(.5);
hSResidplus42_O->SetFillColor(18);
hSResidplus42_O->GetXaxis()->SetTitle("Position (cm)");
hSResidplus42_O->Draw("");
hSResidplus42_N->Draw("epSAME");
leg->Draw("SAME");
c1->Print("hSResidplus42.png");

TH1F * hSResidminus42_N = (TH1F*)fNew->Get("Resolution/hSResid-42");
TH1F * hSResidminus42_O = (TH1F*)fOld->Get("Resolution/hSResid-42");
std::cout<<"h->Fill(endcap[19],"<<hSResidminus42_N->GetMean()<<");"<<std::endl;
std::cout<<"h->SetBinError(19,"<<hSResidminus42_N->GetRMS()<<");"<<std::endl;
std::cout<<hSResidminus42_N->GetMean()<<std::endl;
std::cout<<hSResidminus42_N->GetRMS()<<std::endl;
hSResidminus42_N->SetLineColor(4);
hSResidminus42_N->SetMarkerColor(4);
hSResidminus42_N->SetLineWidth(2);
hSResidminus42_N->SetMarkerSize(.5);
hSResidminus42_O->SetFillColor(18);
hSResidminus42_O->GetXaxis()->SetTitle("Position (cm)");
hSResidminus42_O->Draw("");
hSResidminus42_N->Draw("epSAME");
leg->Draw("SAME");
c1->Print("hSResidminus42.png");


}


